---
- name: Debian-based Systems Playbook
  hosts: debian_servers
  become: yes  # Run tasks with elevated privileges (sudo)

  tasks:
    - name: Update package cache and install a package
      apt:
        name: your_package_name
        state: latest  # You can use 'present' for other package managers
